# Generated by Django 3.1.7 on 2021-10-25 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('registration_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('doctor_name', models.CharField(default='', max_length=50)),
                ('degree', models.CharField(default='', max_length=30)),
                ('designation', models.CharField(default='', max_length=30)),
                ('mail_id', models.EmailField(default='', max_length=254)),
                ('phone_no', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('registration_id', models.CharField(default='', max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(default='', max_length=30)),
                ('mail_id', models.EmailField(default='', max_length=254)),
                ('phone_no', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FridayChamber',
            fields=[
                ('friday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MondayChamber',
            fields=[
                ('monday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='SaturdayChamber',
            fields=[
                ('saturday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='SundayChamber',
            fields=[
                ('sunday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='ThursdayChamber',
            fields=[
                ('thursday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='TuesdayChamber',
            fields=[
                ('tuesday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='WednesdayChamber',
            fields=[
                ('wednesday_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Chamber',
            fields=[
                ('chamber_id', models.AutoField(primary_key=True, serialize=False)),
                ('chamber_location', models.CharField(default='', max_length=30)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.doctor')),
                ('friday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.fridaychamber')),
                ('monday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.mondaychamber')),
                ('saturday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.saturdaychamber')),
                ('sunday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.sundaychamber')),
                ('thursday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.thursdaychamber')),
                ('tuesday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.tuesdaychamber')),
                ('wednesday_chamber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.wednesdaychamber')),
            ],
        ),
    ]
