# Generated by Django 3.1.7 on 2021-10-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0002_auto_20211025_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='friday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.fridaychamber'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='monday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.mondaychamber'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='saturday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.saturdaychamber'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='thursday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.thursdaychamber'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='tuesday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.tuesdaychamber'),
        ),
        migrations.AlterField(
            model_name='chamber',
            name='wednesday_chamber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.wednesdaychamber'),
        ),
        migrations.AlterField(
            model_name='fridaychamber',
            name='friday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='mondaychamber',
            name='monday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='saturdaychamber',
            name='saturday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='sundaychamber',
            name='sunday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='thursdaychamber',
            name='thursday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='tuesdaychamber',
            name='tuesday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='wednesdaychamber',
            name='wednesday_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
    ]
