# Generated by Django 3.1.7 on 2021-10-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0003_auto_20211025_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamber',
            name='chamber_location',
        ),
        migrations.AddField(
            model_name='fridaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='mondaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='saturdaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sundaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='thursdaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tuesdaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='wednesdaychamber',
            name='chamber_location',
            field=models.CharField(default='', max_length=30),
        ),
    ]
