# Generated by Django 3.1.7 on 2021-10-25 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0005_auto_20211025_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaychamber',
            name='friday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='mondaychamber',
            name='monday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='saturdaychamber',
            name='saturday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='sundaychamber',
            name='sunday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='thursdaychamber',
            name='thursday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='tuesdaychamber',
            name='tuesday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='wednesdaychamber',
            name='wednesday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ezhealth_db.doctor'),
        ),
    ]
