# Generated by Django 3.1.7 on 2021-10-25 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0006_auto_20211025_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamber',
            name='sunday_chamber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.sundaychamber'),
        ),
    ]
