# Generated by Django 3.1.7 on 2021-10-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0008_auto_20211025_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mondaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='saturdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sundaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='thursdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tuesdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wednesdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
    ]
