# Generated by Django 3.1.7 on 2021-10-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0009_auto_20211025_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaychamber',
            name='friday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='friday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='mondaychamber',
            name='monday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='monday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='saturdaychamber',
            name='saturday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='saturday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='sundaychamber',
            name='sunday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sunday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='thursdaychamber',
            name='thursday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='thursday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='tuesdaychamber',
            name='tuesday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tuesday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AddField(
            model_name='wednesdaychamber',
            name='wednesday_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='wednesday_name', to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='fridaychamber',
            name='friday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='friday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='mondaychamber',
            name='monday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='monday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='saturdaychamber',
            name='saturday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saturday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='sundaychamber',
            name='sunday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='sunday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='thursdaychamber',
            name='thursday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='thursday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='tuesdaychamber',
            name='tuesday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tuesday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
        migrations.AlterField(
            model_name='wednesdaychamber',
            name='wednesday_id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wednesday_id', serialize=False, to='ezhealth_db.doctor'),
        ),
    ]
