# Generated by Django 3.1.7 on 2021-10-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0010_auto_20211025_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='mondaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='saturdaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='sundaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='thursdaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='tuesdaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='wednesdaychamber',
            name='available_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
