# Generated by Django 3.1.7 on 2021-11-01 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0012_auto_20211030_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(default='', primary_key=True, serialize=False)),
                ('doctor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.doctor')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ezhealth_db.user')),
            ],
        ),
    ]
