# Generated by Django 3.1.7 on 2021-11-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0013_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_registration_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
