# Generated by Django 3.1.7 on 2021-11-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0016_auto_20211110_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_description',
            field=models.TextField(default=''),
        ),
    ]
