# Generated by Django 3.1.7 on 2021-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0017_doctor_doctor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='mondaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='saturdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='sundaychamber',
            name='slots_available',
            field=models.IntegerField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='thursdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='tuesdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='wednesdaychamber',
            name='slots_available',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
