# Generated by Django 3.1.7 on 2021-11-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0019_auto_20211120_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sundaychamber',
            name='slots_available',
            field=models.IntegerField(default=0),
        ),
    ]
