# Generated by Django 3.1.7 on 2021-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0022_appointment_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridaychamber',
            name='friday',
            field=models.CharField(default='friday', max_length=10),
        ),
        migrations.AddField(
            model_name='mondaychamber',
            name='monday',
            field=models.CharField(default='monday', max_length=10),
        ),
        migrations.AddField(
            model_name='saturdaychamber',
            name='saturday',
            field=models.CharField(default='saturday', max_length=10),
        ),
        migrations.AddField(
            model_name='sundaychamber',
            name='sunday',
            field=models.CharField(default='sunday', max_length=10),
        ),
        migrations.AddField(
            model_name='thursdaychamber',
            name='thursday',
            field=models.CharField(default='thursday', max_length=10),
        ),
        migrations.AddField(
            model_name='tuesdaychamber',
            name='tuesday',
            field=models.CharField(default='tuesday', max_length=10),
        ),
        migrations.AddField(
            model_name='wednesdaychamber',
            name='wednesday',
            field=models.CharField(default='wednesday', max_length=10),
        ),
    ]
