# Generated by Django 3.1.7 on 2022-01-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezhealth_db', '0025_doctor_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(default='', max_length=10),
        ),
    ]
